export const ROOT = '/'
export const DASHBOARDS_PREFIX_PATH = '/dashboards'
export const REGISTER_PREFIX_PATH = '/register'
export const AUTH_PREFIX_PATH = '/auth'
export const UI_COMPONENTS_PREFIX_PATH = '/ui-components'
export const PAGES_PREFIX_PATH = '/pages'
export const GUIDE_PREFIX_PATH = '/guide'