version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: N&xu$@d0r141
      POSTGRES_DB: auth_database
      POSTGRES_MULTIPLE_DATABASES: cadastro_database,tarefas_database
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

networks:
  default:
    name: banco_nexus