version: '3.8'

services:
  postgres_cadastro:
    image: postgres:latest
    environment:
      POSTGRES_USER: cadastro_user
      POSTGRES_PASSWORD: N&xu$@d0r141
      POSTGRES_DB: cadastro_database
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_cadastro:/var/lib/postgresql/data

  postgres_auth:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: N&xu$@uth141
      POSTGRES_DB: auth_database
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres_auth:/var/lib/postgresql/data

networks:
  default:
    name: banco_nexus