// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Cadastro.Infra.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Cadastro.Infra.Migrations
{
    [DbContext(typeof(CadastroDbContext))]
    [Migration("20250222145020_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Core.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasDiscriminator<string>("CompanyType").HasValue("Company");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nexus.Cadastro.Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("Nexus.Core.Domain.Entities.Company");

                    b.Property<Guid>("ContabilidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasIndex("ContabilidadeId");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Nexus.Cadastro.Domain.Entities.Contabilidade", b =>
                {
                    b.HasBaseType("Nexus.Core.Domain.Entities.Company");

                    b.HasDiscriminator().HasValue("Contabilidade");
                });

            modelBuilder.Entity("Nexus.Cadastro.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Nexus.Cadastro.Domain.Entities.Contabilidade", "Contabilidade")
                        .WithMany("Clientes")
                        .HasForeignKey("ContabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contabilidade");
                });

            modelBuilder.Entity("Nexus.Cadastro.Domain.Entities.Contabilidade", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
